# COURSE: A deep understanding of deep learning
## SECTION: Math prerequisites
### LECTURE: Matrix multiplication
#### TEACHER: Mike X Cohen, sincxpress.com
##### COURSE URL: udemy.com/course/deeplearning_x/?couponCode=202305

In [10]:
# import libraries
import numpy as np
import torch

# Using numpy

In [11]:
# create some random matrices
A = np.random.randn(3,4)
B = np.random.randn(4,5)
C = np.random.randn(3,7)

# try some multiplications...
print(np.round( A@B   ,2)), print(' ')
# print(np.round( A@C   ,2)), print(' ')
# print(np.round( B@C   ,2)), print(' ')
print(np.round( C.T@A ,2))

[[ 0.05 -0.23 -1.98  2.13 -0.75]
 [-0.19 -1.   -1.69  4.86 -0.97]
 [ 0.23 -1.26 -0.3   3.42 -0.19]]
 
[[-0.9   0.85  0.18  1.02]
 [-1.94  1.41 -1.95  2.52]
 [ 2.13 -1.99  2.44 -2.87]
 [-2.11  2.13 -3.18  2.98]
 [ 1.01 -0.63  1.05 -1.31]
 [ 2.94 -2.87  4.17 -4.1 ]
 [ 0.08 -1.27  0.09 -0.23]]


# Using pytorch

In [12]:
# create some random matrices
A  = torch.randn(3,4)
B  = torch.randn(4,5)
C1 = np.random.randn(4,7)
C2 = torch.tensor( C1,dtype=torch.float )

# try some multiplications...
# print(np.round( A@B   ,2)), print(' ')
# print(np.round( A@B.T ,2)), print(' ')
print(np.round( A@C1  ,2)), print(' ')
print(np.round( A@C2  ,2))

tensor([[-0.2800,  0.4500, -0.1500,  0.7500,  2.0400,  0.8200, -1.0700],
        [-1.5000, -0.6100, -2.2800, -1.4600, -5.5500,  0.0800,  1.8700],
        [-2.0300, -1.2300, -1.0400,  0.5900,  1.3800,  0.4300, -1.0700]],
       dtype=torch.float64)
 
tensor([[-0.2800,  0.4500, -0.1500,  0.7500,  2.0400,  0.8200, -1.0700],
        [-1.5000, -0.6100, -2.2800, -1.4600, -5.5500,  0.0800,  1.8700],
        [-2.0300, -1.2300, -1.0400,  0.5900,  1.3800,  0.4300, -1.0700]])
