# COURSE: A deep understanding of deep learning
## SECTION: ANNs
### LECTURE: Depth vs. breadth: number of parameters
#### TEACHER: Mike X Cohen, sincxpress.com
##### COURSE URL: udemy.com/course/deeplearning_x/?couponCode=202305

In [1]:
# import libraries
import numpy as np
import torch
import torch.nn as nn

In [2]:
# build two models

widenet = nn.Sequential(
    nn.Linear(2, 4),  # hidden layer
    nn.Linear(4, 3),  # output layer
)

deepnet = nn.Sequential(
    nn.Linear(2, 2),  # hidden layer
    nn.Linear(2, 2),  # hidden layer
    nn.Linear(2, 3),  # output layer
)

# print them out to have a look
print(widenet)
print(' ')
print(deepnet)

Sequential(
  (0): Linear(in_features=2, out_features=4, bias=True)
  (1): Linear(in_features=4, out_features=3, bias=True)
)
 
Sequential(
  (0): Linear(in_features=2, out_features=2, bias=True)
  (1): Linear(in_features=2, out_features=2, bias=True)
  (2): Linear(in_features=2, out_features=3, bias=True)
)


# Peeking inside the network

In [3]:
# check out the parameters
for p in deepnet.named_parameters():
    print(p)
    print(' ')

('0.weight', Parameter containing:
tensor([[ 0.1277, -0.6143],
        [ 0.1280, -0.5710]], requires_grad=True))
 
('0.bias', Parameter containing:
tensor([-0.4916, -0.6252], requires_grad=True))
 
('1.weight', Parameter containing:
tensor([[ 0.4578,  0.2879],
        [ 0.6127, -0.0146]], requires_grad=True))
 
('1.bias', Parameter containing:
tensor([-0.7051, -0.6852], requires_grad=True))
 
('2.weight', Parameter containing:
tensor([[-0.4974,  0.1828],
        [ 0.6582,  0.1277],
        [-0.6517,  0.2251]], requires_grad=True))
 
('2.bias', Parameter containing:
tensor([-0.6877, -0.1765, -0.1066], requires_grad=True))
 


In [4]:
# count the number of nodes ( = the number of biases)

# named_parameters() is an iterable that returns the tuple (name,numbers)
numNodesInWide = 0
for p in widenet.named_parameters():
    if 'bias' in p[0]:
        numNodesInWide += len(p[1])

numNodesInDeep = 0
for paramName, paramVect in deepnet.named_parameters():
    if 'bias' in paramName:
        numNodesInDeep += len(paramVect)

print('There are %s nodes in the wide network.' % numNodesInWide)
print('There are %s nodes in the deep network.' % numNodesInDeep)

There are 7 nodes in the wide network.
There are 7 nodes in the deep network.


In [ ]:
# just the parameters
for p in widenet.parameters():
    print(p)
    print(' ')

In [5]:
# now count the total number of trainable parameters
nparams = 0
for p in widenet.parameters():
    if p.requires_grad:
        print('This piece has %s parameters' % p.numel())
        nparams += p.numel()

print('\n\nTotal of %s parameters' % nparams)

This piece has 8 parameters
This piece has 4 parameters
This piece has 12 parameters
This piece has 3 parameters


Total of 27 parameters


In [6]:
# btw, can also use list comprehension

nparams = np.sum([p.numel() for p in widenet.parameters() if p.requires_grad])
print('Widenet has %s parameters' % nparams)

nparams = np.sum([p.numel() for p in deepnet.parameters() if p.requires_grad])
print('Deepnet has %s parameters' % nparams)

Widenet has 27 parameters
Deepnet has 21 parameters


In [9]:
# A nice simple way to print out the model info.
from torchinfo import summary

summary(widenet, (1, 2))

### NOTE ABOUT THE CODE IN THIS CELL:
# torchsummary is being replaced by torchinfo.
# If you are importing these libraries on your own (via pip), then see the following website:
#        https://pypi.org/project/torch-summary/
# However, torchsummary will continue to be supported, so if the code in this cell works (meaning torchsummary is already installed), 
# then you don't need to do anything!

Layer (type:depth-idx)                   Output Shape              Param #
Sequential                               [1, 3]                    --
├─Linear: 1-1                            [1, 4]                    12
├─Linear: 1-2                            [1, 3]                    15
Total params: 27
Trainable params: 27
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00